/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianScholarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/constants.ts
var ARXIV_BIBTEX_API = "https://arxiv.org/bibtex/";
var ARXIV_REST_API = "https://export.arxiv.org/api/query?id_list=";
var ARXIV_URL_SUFFIX_ON_S2 = "arXiv:";
var ACL_ANTHOLOGY_URL_SUFFIX_ON_S2 = "ACL:";
var SEMANTIC_SCHOLAR_FIELDS = "fields=authors,title,abstract,url,venue,year,publicationDate,externalIds,isOpenAccess,openAccessPdf,citationStyles&limit=50";
var SEMANTIC_SCHOLAR_API = "https://api.semanticscholar.org/graph/v1/paper/";
var SEMANTIC_SCHOLAR_SEARCH_API = "https://api.semanticscholar.org/graph/v1/paper/search/?query=";
var SEMANTIC_SCHOLAR_REFERENCE_SEARCH_FIELDS = "/references?fields=authors,title,abstract,url,venue,year,publicationDate,externalIds,isOpenAccess,openAccessPdf,citationStyles&limit=50";
var COMMAND_PAPER_NOTE_ID = "create-paper-note-from-url";
var COMMAND_PAPER_NOTE_NAME = "Add paper to Library";
var COMMAND_PAPER_MODAL_TITLE = "Enter a Paper URL";
var COMMAND_PAPER_MODAL_PLACEHOLDERS = [
  "https://arxiv.org/abs/xxxx.xxxx",
  "https://aclanthology.org/2022.acl-long.1/",
  "https://www.semanticscholar.org/paper/some-text/xxxx"
];
var COMMAND_PAPER_MODAL_DESC = "Right now we support paper URLs from arXiv, Semantic Scholar, and ACL Anthology.";
var COMMAND_SEARCH_PAPER = "search-paper";
var COMMAND_SEARCH_PAPER_NAME = "Search Paper";
var COMMAND_COPY_PAPER_BIBTEX = "copy-paper-bibtex";
var COMMAND_COPY_PAPER_BIBTEX_NAME = "Copy Paper BibTeX";
var COMMAND_SEARCH_PAPER_REFERENCES = "search-paper-references";
var COMMAND_SEARCH_PAPER_REFERENCES_NAME = "Search Paper References";
var COMMAND_REMOVE_PAPER = "remove-paper";
var COMMAND_REMOVE_PAPER_NAME = "Remove Paper from Library";
var COMMAND_OPEN_PDF_IN_SYSTEM_APP = "open-pdf-in-system-app";
var COMMAND_OPEN_PDF_IN_SYSTEM_APP_NAME = "Open PDF in System App";
var SETTING_GENERAL_HEADER = "Library Settings";
var SETTING_NOTE_FOLDER_NAME = "Note folder";
var SETTING_NOTE_FOLDER_DESC = "Folder to create paper notes in.";
var SETTING_NOTE_FOLDER_DEFAULT = "(root of the vault)";
var SETTING_PDF_DOWNLOAD_NAME = "PDF folder";
var SETTING_PDF_DOWNLOAD_DESC = "Choose the path to download the PDF to.";
var SETTING_PDF_DOWNLOAD_FOLDER_DEFAULT = "(root of the vault)";
var SETTING_IS_OPEN_PDF_WITH_NOTE_NAME = "Open PDF with note?";
var SETTING_IS_OPEN_PDF_WITH_NOTE_DESC = "Whether to open the PDF alongside the note.";
var SETTING_IS_ADD_TO_BIB_FILE_NAME = "Save paper BibTeX to a .bib file?";
var SETTING_IS_ADD_TO_BIB_FILE_DESC = 'If disabled, you cannot execute the "Copy Paper BibTeX" command.';
var SETTING_ADD_TO_BIB_FILE_NAME = "Save the BibTeX to";
var SETTING_ADD_TO_BIB_FILE_DESC = "Choose the .bib file to save the BibTeX to.";
var SETTING_NOTE_HEADER = "Note Settings";
var SETTING_FRONTMATTER_ADD_ALIASES_NAME = "Add aliases key in the note frontmatter?";
var SETTING_FRONTMATTER_ADD_ALIASES_DESC = "If enabled, it will add the @{{citeky}} as an alias to the note.";
var SETTING_FRONTMATTER_ADD_ANNOTATION_NAME = "Add annotation key in the note frontmatter?";
var SETTING_FRONTMATTER_ADD_ANNOTATION_DESC = "If enabled, it will add the annotation-target key; use with the Annotator plugin.";
var SETTING_TEMPLATE_NAME = "Note Template";
var SETTING_TEMPLATE_DESC = "If set, we will use you own template for the paper note.";
var NOTICE_RETRIEVING_ARXIV = "Retrieving paper information from arXiv API.";
var NOTICE_RETRIEVING_S2 = "Retrieving paper information from Semantic Scholar API.";
var NOTICE_DOWNLOADING_S2 = "Downloading Paper From S2";
var NOTICE_NOT_BIB_FILE = "The file you selected is not a .bib file.";
var NOTICE_NO_BIB_FILE_SELECTED = "No .bib file is selected. Please create one first.";
var NOTICE_PAPER_NOTE_DOWNLOAD_ERROR = "Something went wrong. Check the Obsidian console if the error persists.";
var FILE_ALREADY_EXISTS = "Unable to create note. File already exists. Opening existing file.";
var NOTICE_SEARCH_BIBTEX_NOT_FOUND = "The BibTeX for this paper is not found. You might search the bibtext file manually.";
var NOTICE_SEARCH_BIBTEX_ERROR = "The BibTeX for this paper is not found. You might search the bibtext file manually.";
var NOTICE_SEARCH_BIBTEX_COPIED = "The BibTeX of this paper is copied to the clipboard.";
var NOTE_FRONTMATTER_DEFAULT = `title: "{{title}}"
added: "{{date}}"
authors: "{{authors}}"
tags: 
url: "{{url}}"
pdf: "{{pdf}}"
citekey: "{{citekey}}"
abstract: "{{abstract}}"`;
var NOTE_FRONTMATTER_ALIASES = `aliases: "@{{citekey}}"`;
var NOTE_FRONTMATTER_ANNOTATION = `annotation-target: "{{pdf}}"`;

// src/paperData.ts
var import_obsidian2 = require("obsidian");

// src/utility.ts
var import_obsidian = require("obsidian");
function getDate(input) {
  let duration;
  if ((input == null ? void 0 : input.offset) !== null && (input == null ? void 0 : input.offset) !== void 0 && typeof input.offset === "number") {
    duration = window.moment.duration(input.offset, "days");
  }
  return (input == null ? void 0 : input.format) ? window.moment().add(duration).format(input.format) : window.moment().add(duration).format("YYYY-MM-DD");
}
function trimString(str) {
  if (str == null)
    return "";
  return str.replace(/\s+/g, " ").trim();
}
function isValidUrl(s) {
  var regex = /^(https?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(\:\d+)?(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(\#[-a-z\d_]*)?$/i;
  return !!regex.test(s);
}
function splitBibtex(bibtex) {
  let regex = /(@.*?{[^@]*})/gs;
  return bibtex.match(regex);
}
function getSystemPathSeparator() {
  return import_obsidian.Platform.isWin ? "\\" : "/";
}

// src/paperData.ts
function getIdentifierFromUrl(url) {
  if (url.endsWith("/"))
    url = url.slice(0, -1);
  return url.split("/").slice(-1)[0];
}
function getCiteKeyFromBibtex(bibtex) {
  const match = bibtex.match(/@.*\{([^,]+)/);
  return match ? match[1] : null;
}
async function fetchArxivBibtex(arxivId) {
  const bibtex = await (0, import_obsidian2.request)(ARXIV_BIBTEX_API + arxivId);
  return bibtex;
}
async function fetchArxivPaperDataFromUrl(url) {
  var _a;
  const arxivId = getIdentifierFromUrl(url);
  const arxivData = await (0, import_obsidian2.request)(ARXIV_REST_API + arxivId);
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(arxivData, "text/xml");
  let title = xmlDoc.getElementsByTagName("title")[1].textContent;
  let abstract = xmlDoc.getElementsByTagName("summary")[0].textContent;
  let authorsSource = xmlDoc.getElementsByTagName("author");
  let authors = [];
  for (let i = 0; i < authorsSource.length; i++) {
    authors.push(
      authorsSource[i].getElementsByTagName("name")[0].textContent
    );
  }
  let date = xmlDoc.getElementsByTagName("published")[0].textContent;
  if (date)
    date = date.split("T")[0];
  if (title == null)
    title = "undefined";
  let pdfUrl = (_a = xmlDoc.querySelector('link[title="pdf"]')) == null ? void 0 : _a.getAttribute("href");
  let bibtex = await fetchArxivBibtex(arxivId);
  return {
    title: trimString(title),
    authors,
    url: trimString(url),
    publicationDate: trimString(date),
    abstract: trimString(abstract),
    pdfUrl,
    bibtex,
    citekey: getCiteKeyFromBibtex(bibtex)
  };
}
function parseS2paperData(json) {
  var _a, _b;
  let title = json.title;
  let abstract = json.abstract;
  let authors = json.authors ? json.authors.map((author) => author.name) : [];
  let venue = "";
  if (json.venue != null && json.venue != "")
    venue = json.venue + " " + json.year;
  let publicationDate = json.publicationDate;
  if (title == null)
    title = "undefined";
  let paperUrl = json.url;
  let pdfUrl = "";
  if (json["isOpenAccess"] && json["isOpenAccess"] === true && json["openAccessPdf"]) {
    pdfUrl = (_a = json["openAccessPdf"]) == null ? void 0 : _a.url;
  }
  if (json["externalIds"] && json["externalIds"]["ArXiv"]) {
    paperUrl = "https://arxiv.org/abs/" + json.externalIds["ArXiv"];
    pdfUrl = "https://arxiv.org/pdf/" + json.externalIds["ArXiv"];
  }
  if (json["externalIds"] && json["externalIds"]["ACL]"]) {
    paperUrl = "https://aclanthology.org/" + json.externalIds["ACL"];
    let pdfUrl2 = paperUrl;
    if (pdfUrl2.endsWith("/")) {
      pdfUrl2 = paperUrl.slice(0, -1);
    }
    pdfUrl2 = pdfUrl2 + ".pdf";
  }
  let bibtex = ((_b = json["citationStyles"]) == null ? void 0 : _b.bibtex) ? json["citationStyles"]["bibtex"] : "";
  return {
    title: trimString(title),
    authors,
    venue: trimString(venue),
    url: paperUrl,
    publicationDate: trimString(publicationDate),
    abstract: trimString(abstract),
    pdfUrl,
    bibtex,
    citekey: getCiteKeyFromBibtex(bibtex)
  };
}
async function fetchSemanticScholarPaperDataFromUrl(url) {
  let s2Id = getIdentifierFromUrl(url);
  if (url.toLowerCase().includes("arxiv")) {
    s2Id = ARXIV_URL_SUFFIX_ON_S2 + s2Id.split("v")[0];
  } else if (url.toLowerCase().includes("aclanthology")) {
    s2Id = ACL_ANTHOLOGY_URL_SUFFIX_ON_S2 + s2Id;
  } else if (url.toLowerCase().includes("semanticscholar")) {
  } else {
    console.log("Invalid url: " + url);
    throw new Error("Invalid url: " + url);
  }
  let s2Data = await (0, import_obsidian2.request)(
    SEMANTIC_SCHOLAR_API + s2Id + "?" + SEMANTIC_SCHOLAR_FIELDS
  );
  let json = JSON.parse(s2Data);
  if (json.error != null) {
    throw new Error(json.error);
  }
  return parseS2paperData(json);
}
async function searchSemanticScholar(query) {
  let requestUrl2 = SEMANTIC_SCHOLAR_SEARCH_API + encodeURIComponent(query) + "&" + SEMANTIC_SCHOLAR_FIELDS;
  let s2Data = await (0, import_obsidian2.request)(requestUrl2);
  let json = JSON.parse(s2Data);
  if (json.error != null) {
    throw new Error(json.error);
  }
  if (json.data == null || json.data.length == 0 || (json == null ? void 0 : json.total) == 0) {
    throw new Error("No data returned");
  }
  return json.data.map((paper) => parseS2paperData(paper));
}
async function fetchSemanticScholarPaperReferences(url) {
  let s2Id = getIdentifierFromUrl(url);
  if (url.toLowerCase().includes("arxiv")) {
    s2Id = ARXIV_URL_SUFFIX_ON_S2 + s2Id.split("v")[0];
  } else if (url.toLowerCase().includes("aclanthology")) {
    s2Id = ACL_ANTHOLOGY_URL_SUFFIX_ON_S2 + s2Id;
  } else if (url.toLowerCase().includes("semanticscholar")) {
  } else {
    console.log("Invalid url: " + url);
    throw new Error("Invalid url: " + url);
  }
  let s2Data = await (0, import_obsidian2.request)(
    SEMANTIC_SCHOLAR_API + s2Id + SEMANTIC_SCHOLAR_REFERENCE_SEARCH_FIELDS
  );
  let json = JSON.parse(s2Data);
  if (json.error != null) {
    throw new Error(json.error);
  }
  if (json.data == null || json.data.length == 0 || (json == null ? void 0 : json.total) == 0) {
    throw new Error("No data returned");
  }
  return json.data.map(
    (citedPaperData) => parseS2paperData(citedPaperData["citedPaper"])
  );
}

// src/settingsTab.ts
var import_obsidian3 = require("obsidian");
var DEFAULT_SETTINGS = {
  NoteLocation: "",
  fileNaming: "",
  templateFileLocation: "",
  pdfDownloadLocation: "",
  openPdfAfterDownload: false,
  saveBibTex: false,
  bibTexFileLocation: "",
  noteAddFrontmatterAliases: false,
  noteAddFrontmatterAnnotation: false
};
var ObsidianScholarSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: SETTING_GENERAL_HEADER });
    let folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian3.TFolder && f.path !== "/").map((f) => f.path);
    let folderOptions = {};
    folders.forEach((record) => {
      folderOptions[record] = record;
    });
    folderOptions[""] = SETTING_NOTE_FOLDER_DEFAULT;
    let pdfDownloadFolderOptions = {};
    folders.forEach((record) => {
      pdfDownloadFolderOptions[record] = record;
    });
    pdfDownloadFolderOptions[""] = SETTING_PDF_DOWNLOAD_FOLDER_DEFAULT;
    let allFiles = this.app.vault.getAllLoadedFiles().map((f) => f.path);
    let bibTexSaveOption = {};
    allFiles.forEach((record) => {
      bibTexSaveOption[record] = record;
    });
    bibTexSaveOption[""] = "";
    new import_obsidian3.Setting(containerEl).setName(SETTING_NOTE_FOLDER_NAME).setDesc(SETTING_NOTE_FOLDER_DESC).addDropdown(
      (dropdown) => dropdown.addOptions(folderOptions).setValue(this.plugin.settings.NoteLocation).onChange(async (value) => {
        this.plugin.settings.NoteLocation = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(SETTING_PDF_DOWNLOAD_NAME).setDesc(SETTING_PDF_DOWNLOAD_DESC).addDropdown(
      (dropdown) => dropdown.addOptions(pdfDownloadFolderOptions).setValue(this.plugin.settings.pdfDownloadLocation).onChange(async (value) => {
        this.plugin.settings.pdfDownloadLocation = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(SETTING_IS_OPEN_PDF_WITH_NOTE_NAME).setDesc(SETTING_IS_OPEN_PDF_WITH_NOTE_DESC).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.openPdfAfterDownload).onChange(async (openPdfAfterDownload) => {
        this.plugin.settings.openPdfAfterDownload = openPdfAfterDownload;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(SETTING_IS_ADD_TO_BIB_FILE_NAME).setDesc(SETTING_IS_ADD_TO_BIB_FILE_DESC).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.saveBibTex).onChange(async (saveBibTex) => {
        if (saveBibTex) {
          new import_obsidian3.Setting(containerEl).setName(SETTING_ADD_TO_BIB_FILE_NAME).setDesc(SETTING_ADD_TO_BIB_FILE_DESC).addDropdown(
            (dropdown) => dropdown.addOptions(bibTexSaveOption).setValue(
              this.plugin.settings.bibTexFileLocation
            ).onChange(async (value) => {
              if (!value.endsWith(".bib")) {
                new import_obsidian3.Notice(NOTICE_NOT_BIB_FILE);
              }
              if (value === "" || value === void 0 || value === null) {
                new import_obsidian3.Notice(
                  NOTICE_NO_BIB_FILE_SELECTED
                );
                return;
              }
              this.plugin.settings.bibTexFileLocation = value;
              this.plugin.settings.saveBibTex = saveBibTex;
              await this.plugin.saveSettings();
            })
          );
        } else {
          this.plugin.settings.saveBibTex = saveBibTex;
          containerEl.removeChild(containerEl.lastChild);
        }
      })
    );
    if (this.plugin.settings.saveBibTex) {
      new import_obsidian3.Setting(containerEl).setName(SETTING_ADD_TO_BIB_FILE_NAME).setDesc(SETTING_ADD_TO_BIB_FILE_DESC).addDropdown(
        (dropdown) => dropdown.addOptions(bibTexSaveOption).setValue(this.plugin.settings.bibTexFileLocation).onChange(async (value) => {
          if (!value.endsWith(".bib")) {
            new import_obsidian3.Notice(NOTICE_NOT_BIB_FILE);
          }
          this.plugin.settings.bibTexFileLocation = value;
          await this.plugin.saveSettings();
        })
      );
    }
    containerEl.createEl("h2", { text: SETTING_NOTE_HEADER });
    new import_obsidian3.Setting(containerEl).setName(SETTING_FRONTMATTER_ADD_ALIASES_NAME).setDesc(SETTING_FRONTMATTER_ADD_ALIASES_DESC).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.noteAddFrontmatterAliases).onChange(async (value) => {
        this.plugin.settings.noteAddFrontmatterAliases = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName(SETTING_FRONTMATTER_ADD_ANNOTATION_NAME).setDesc(SETTING_FRONTMATTER_ADD_ANNOTATION_DESC).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.noteAddFrontmatterAnnotation).onChange(async (value) => {
        this.plugin.settings.noteAddFrontmatterAnnotation = value;
        await this.plugin.saveSettings();
      })
    );
    let files = this.app.vault.getMarkdownFiles().map((file) => file.path);
    let templateOptions = {};
    files.forEach((record) => {
      templateOptions[record] = record;
    });
    templateOptions[""] = "(none)";
    new import_obsidian3.Setting(containerEl).setName(SETTING_TEMPLATE_NAME).setDesc(SETTING_TEMPLATE_DESC).addDropdown(
      (dropdown) => dropdown.addOptions(templateOptions).setValue(this.plugin.settings.templateFileLocation).onChange(async (value) => {
        this.plugin.settings.templateFileLocation = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/obsidianScholar.ts
var import_obsidian4 = require("obsidian");
var import_child_process = require("child_process");
var ObsidianScholar = class {
  constructor(app, settings, pathSep) {
    this.app = app;
    this.settings = settings;
    this.pathSep = pathSep ? pathSep : "/";
  }
  constructFileName(paperData) {
    return paperData.title.replace(/[^a-zA-Z0-9 ]/g, "");
  }
  getPaperDataFromLocalFile(file) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j;
    let fileCache = this.app.metadataCache.getFileCache(file);
    let frontmatter = fileCache == null ? void 0 : fileCache.frontmatter;
    let pdfPath = (_a = frontmatter == null ? void 0 : frontmatter.pdf) != null ? _a : "";
    let matchedPdfPath = pdfPath.match(/\[\[(.*?)\]\]/);
    if (matchedPdfPath) {
      pdfPath = matchedPdfPath[1];
    } else {
      pdfPath = "";
    }
    return {
      title: (_b = frontmatter == null ? void 0 : frontmatter.title) != null ? _b : file.basename,
      authors: (_c = frontmatter == null ? void 0 : frontmatter.authors.split(",")) != null ? _c : [],
      abstract: (_d = frontmatter == null ? void 0 : frontmatter.abstract) != null ? _d : null,
      url: (_e = frontmatter == null ? void 0 : frontmatter.url) != null ? _e : null,
      venue: (_f = frontmatter == null ? void 0 : frontmatter.venue) != null ? _f : null,
      publicationDate: (_g = frontmatter == null ? void 0 : frontmatter.year) != null ? _g : null,
      tags: (_h = frontmatter == null ? void 0 : frontmatter.tags) != null ? _h : [],
      pdfPath,
      citekey: (_i = frontmatter == null ? void 0 : frontmatter.citekey) != null ? _i : null,
      bibtex: (_j = frontmatter == null ? void 0 : frontmatter.bibtex) != null ? _j : null
    };
  }
  detachAllUnpinnedLeaves() {
    this.app.workspace.iterateRootLeaves((leaf) => {
      if (leaf.getViewState().state.pinned)
        return;
      sleep(0).then(() => {
        leaf.detach();
      });
    });
  }
  async getAllLocalPaperData() {
    return this.app.vault.getMarkdownFiles().filter((file) => file.path.startsWith(this.settings.NoteLocation)).map((file) => {
      return this.getPaperDataFromLocalFile(file);
    });
  }
  isFileInNoteLocation(file) {
    if (typeof file === "string") {
      return file.startsWith(this.settings.NoteLocation);
    } else {
      return file.path.startsWith(this.settings.NoteLocation);
    }
  }
  async extractPaperBibtexFromFile(citekey) {
    if (!this.settings.saveBibTex || this.settings.bibTexFileLocation === "") {
      return void 0;
    }
    let bibtextFile = this.app.vault.getAbstractFileByPath(
      this.settings.bibTexFileLocation
    );
    if (bibtextFile == null || !(bibtextFile instanceof import_obsidian4.TFile)) {
      new import_obsidian4.Notice("BibTex file not found.");
      return;
    }
    let bibtexText = await this.app.vault.adapter.read(
      this.settings.bibTexFileLocation
    );
    let bibtexEntries = splitBibtex(bibtexText);
    if (!bibtexEntries) {
      new import_obsidian4.Notice("BibTex file is empty.");
      return;
    }
    for (let entry of bibtexEntries) {
      if (entry.includes(citekey)) {
        return entry;
      }
    }
    return;
  }
  async getPaperBibtex(file) {
    if (typeof file === "string") {
      file = this.app.vault.getAbstractFileByPath(file);
    }
    let paperData = this.getPaperDataFromLocalFile(file);
    if (paperData.bibtex && paperData.bibtex !== "") {
      return paperData.bibtex;
    }
    if (paperData.citekey && paperData.citekey !== "") {
      return await this.extractPaperBibtexFromFile(paperData.citekey);
    }
  }
  cleanStringForFrontmatter(str) {
    return str.replace("\n", " ").replace(/\\[^bfnrtv0'"\\]/g, "").replace(/"/g, '\\"');
  }
  // prettier-ignore
  async createFileWithTemplate(paperData) {
    var _a;
    let template = "";
    let templateFile = this.app.vault.getAbstractFileByPath(this.settings.templateFileLocation);
    if (templateFile != null && templateFile instanceof import_obsidian4.TFile) {
      template = await this.app.vault.cachedRead(templateFile);
    } else {
      template = "---\n";
      template += NOTE_FRONTMATTER_DEFAULT;
      if (this.settings.noteAddFrontmatterAliases) {
        template += "\n" + NOTE_FRONTMATTER_ALIASES;
      }
      if (this.settings.noteAddFrontmatterAnnotation) {
        template += "\n" + NOTE_FRONTMATTER_ANNOTATION;
      }
      template += "\n---\n\n";
      console.log(template);
    }
    template = template.replace(/{{date}}/g, getDate({ format: "YYYY-MM-DD" }));
    template = template.replace(/{{time}}/g, getDate({ format: "HH:mm" }));
    template = template.replace(/{{date:(.*?)}}/g, (_, format) => getDate({ format }));
    template = template.replace(/{{time:(.*?)}}/g, (_, format) => getDate({ format }));
    template = template.replace(/{{title}}/g, this.cleanStringForFrontmatter(paperData.title));
    template = template.replace(/{{authors}}/g, this.cleanStringForFrontmatter(paperData.authors.join(", ")));
    template = template.replace(/{{abstract}}/g, this.cleanStringForFrontmatter(paperData.abstract));
    template = template.replace(/{{url}}/g, paperData.url ? this.cleanStringForFrontmatter(paperData.url) : "");
    template = template.replace(/{{venue}}/g, paperData.venue ? this.cleanStringForFrontmatter(paperData.venue) : "");
    template = template.replace(/{{publicationDate}}/g, paperData.publicationDate ? this.cleanStringForFrontmatter(paperData.publicationDate) : "");
    template = template.replace(/{{tags}}/g, (_a = (paperData == null ? void 0 : paperData.tags) && this.cleanStringForFrontmatter(paperData.tags.join(", "))) != null ? _a : "");
    template = template.replace(/{{pdf}}/g, paperData.pdfPath ? `[[${paperData.pdfPath}]]` : "");
    if (paperData.citekey) {
      template = template.replace(/{{citekey}}/g, paperData.citekey);
    }
    return template;
  }
  async createFileFromPaperData(paperData, pathToFile) {
    let template = await this.createFileWithTemplate(paperData);
    if (this.settings.openPdfAfterDownload && paperData.pdfPath) {
      this.detachAllUnpinnedLeaves();
    }
    if (await this.app.vault.adapter.exists(pathToFile)) {
      new import_obsidian4.Notice(FILE_ALREADY_EXISTS);
      this.app.workspace.openLinkText(pathToFile, pathToFile);
    } else {
      await this.app.vault.create(pathToFile, template).then(() => {
        this.app.workspace.openLinkText(pathToFile, pathToFile);
      });
    }
    if (this.settings.openPdfAfterDownload) {
      let leaf = this.app.workspace.getLeaf("split", "vertical");
      paperData.pdfPath && leaf.openFile(
        this.app.vault.getAbstractFileByPath(
          paperData.pdfPath
        )
      );
    }
  }
  async openPaper(pathToFile, paperData) {
    if (this.settings.openPdfAfterDownload) {
      this.detachAllUnpinnedLeaves();
      this.app.workspace.openLinkText(pathToFile, pathToFile, true);
      let leaf = this.app.workspace.getLeaf("split", "vertical");
      paperData.pdfPath && leaf.openFile(
        this.app.vault.getAbstractFileByPath(
          paperData.pdfPath
        )
      );
    } else {
      this.app.workspace.openLinkText(pathToFile, pathToFile);
    }
  }
  async downloadPdf(pdfUrl, filename) {
    return new Promise(async (resolve, reject) => {
      if (!pdfUrl) {
        reject("pdfUrl is undefined or null");
        return;
      }
      let pdfDownloadFolder = this.settings.pdfDownloadLocation;
      let pdfSavePath = pdfDownloadFolder + this.pathSep + filename + ".pdf";
      if (await this.app.vault.adapter.exists(pdfSavePath)) {
        resolve(pdfSavePath);
        return;
      }
      (0, import_obsidian4.requestUrl)({
        url: pdfUrl,
        method: "GET"
      }).arrayBuffer.then((arrayBuffer) => {
        this.app.vault.createBinary(pdfSavePath, arrayBuffer).then(() => resolve(pdfSavePath)).catch(reject);
      }).catch(reject);
    });
  }
  async openPdfWithSystemViewer(currentFile) {
    if (!import_obsidian4.Platform.isMacOS) {
      new import_obsidian4.Notice("This feature is only available on macOS.");
      return;
    }
    let pdfPath = "";
    if (currentFile.extension == "md" && this.isFileInNoteLocation(currentFile)) {
      let paperData = this.getPaperDataFromLocalFile(currentFile);
      if (paperData.pdfPath) {
        pdfPath = paperData.pdfPath;
      }
    } else if (currentFile.extension == "pdf") {
      pdfPath = currentFile.path;
    } else {
      new import_obsidian4.Notice("The current file is not a pdf or a note.");
      return;
    }
    let absolutePath = this.app.vault.adapter.getFullPath(pdfPath);
    (0, import_child_process.exec)(`open -a Preview "${absolutePath}"`, (error, stdout, stderr) => {
      if (error) {
        console.error(`exec error: ${error}`);
        return;
      }
    });
  }
  async saveBibTex(bibtex) {
    if (this.settings.saveBibTex === false) {
      return;
    }
    let bibTexPath = this.settings.bibTexFileLocation;
    if (bibTexPath === "") {
      new import_obsidian4.Notice("BibTex location is not set in the settings.");
      return;
    }
    let bibtexText = "";
    if (await this.app.vault.adapter.exists(bibTexPath)) {
      let bibtexText2 = await this.app.vault.adapter.read(bibTexPath);
      if (bibtexText2.includes(bibtex)) {
        new import_obsidian4.Notice("BibTex entry already exists.");
        return;
      }
    }
    let bibtextFile = this.app.vault.getAbstractFileByPath(bibTexPath);
    if (bibtextFile == null || !(bibtextFile instanceof import_obsidian4.TFile)) {
      new import_obsidian4.Notice("BibTex file not found.");
      return;
    }
    this.app.vault.append(bibtextFile, bibtex + "\n\n" + bibtexText).then(() => {
      new import_obsidian4.Notice("BibTex entry saved.");
    }).catch((error) => {
      new import_obsidian4.Notice("Error: " + error);
    });
  }
  async downloadAndSavePaperNotePDF(paperData) {
    let paperFilename = this.constructFileName(paperData);
    if (!paperData.pdfUrl) {
      new import_obsidian4.Notice(
        "No pdf url found. You might need to find the PDF manually."
      );
    } else {
      paperData.pdfPath = await this.downloadPdf(
        paperData.pdfUrl,
        paperFilename
      );
    }
    let pathToFile = this.settings.NoteLocation + this.pathSep + paperFilename + ".md";
    await this.createFileFromPaperData(paperData, pathToFile);
    (paperData == null ? void 0 : paperData.bibtex) && await this.saveBibTex(paperData.bibtex);
  }
  async removePaperFromPath(pathsToFile) {
    let citeKeysToRemove = [];
    for (let pathToFile of pathsToFile) {
      if (await this.app.vault.adapter.exists(pathToFile)) {
        let noteFile = this.app.vault.getAbstractFileByPath(pathToFile);
        if (noteFile == null || !(noteFile instanceof import_obsidian4.TFile)) {
          new import_obsidian4.Notice("Note file not found.");
          return;
        }
        let paperData = this.getPaperDataFromLocalFile(noteFile);
        if (paperData.citekey) {
          citeKeysToRemove.push(paperData.citekey);
        }
        if (paperData.pdfPath) {
          let pdfFile = this.app.vault.getAbstractFileByPath(
            paperData.pdfPath
          );
          if (pdfFile == null || !(pdfFile instanceof import_obsidian4.TFile)) {
            new import_obsidian4.Notice("PDF file not found.");
            return;
          }
          await this.app.vault.delete(pdfFile);
        }
        await this.app.vault.delete(noteFile);
        new import_obsidian4.Notice(
          "Paper " + paperData.title + "removed from the library."
        );
      } else {
        new import_obsidian4.Notice("File" + pathToFile + "not found.");
      }
    }
    if (this.settings.bibTexFileLocation) {
      let bibTexPath = this.settings.bibTexFileLocation;
      let bibtextFile = this.app.vault.getAbstractFileByPath(bibTexPath);
      if (bibtextFile == null || !(bibtextFile instanceof import_obsidian4.TFile)) {
        new import_obsidian4.Notice("BibTex file not found.");
        return;
      }
      let bibtexText = await this.app.vault.adapter.read(
        this.settings.bibTexFileLocation
      );
      let bibtexEntries = splitBibtex(bibtexText);
      if (!bibtexEntries) {
        new import_obsidian4.Notice("BibTex file is empty.");
        return;
      }
      bibtexEntries = bibtexEntries.filter(
        (entry) => !citeKeysToRemove.some((citekey) => entry.includes(citekey))
      );
      let newBibtexText = bibtexEntries.join("\n\n");
      await this.app.vault.adapter.write(
        this.settings.bibTexFileLocation,
        newBibtexText
      );
    }
  }
};

// src/main.ts
var ObsidianScholarPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.obsidianScholar = new ObsidianScholar(
      this.app,
      this.settings,
      getSystemPathSeparator()
    );
    this.addCommand({
      id: COMMAND_PAPER_NOTE_ID,
      name: COMMAND_PAPER_NOTE_NAME,
      callback: () => {
        new createNoteFromUrlModal(
          this.app,
          this.settings,
          this.obsidianScholar
        ).open();
      }
    });
    this.addCommand({
      id: COMMAND_SEARCH_PAPER,
      name: COMMAND_SEARCH_PAPER_NAME,
      callback: () => {
        new paperSearchModal(
          this.app,
          this.settings,
          this.obsidianScholar
        ).open();
      }
    });
    this.addCommand({
      id: COMMAND_COPY_PAPER_BIBTEX,
      name: COMMAND_COPY_PAPER_BIBTEX_NAME,
      checkCallback: (checking) => {
        const currentFile = this.app.workspace.getActiveFile();
        if (!this.settings.saveBibTex || !currentFile || currentFile.extension !== "md" || !this.obsidianScholar.isFileInNoteLocation(currentFile)) {
          return false;
        } else {
          if (!checking) {
            this.obsidianScholar.getPaperBibtex(currentFile).then((bibtex) => {
              if (!bibtex) {
                new import_obsidian5.Notice(NOTICE_SEARCH_BIBTEX_NOT_FOUND);
                return false;
              }
              navigator.clipboard.writeText(bibtex);
              new import_obsidian5.Notice(NOTICE_SEARCH_BIBTEX_COPIED);
            }).catch((err) => {
              console.log(err);
              new import_obsidian5.Notice(NOTICE_SEARCH_BIBTEX_ERROR);
            });
          }
          return true;
        }
      }
    });
    this.addCommand({
      id: COMMAND_SEARCH_PAPER_REFERENCES,
      name: COMMAND_SEARCH_PAPER_REFERENCES_NAME,
      checkCallback: (checking) => {
        const currentFile = this.app.workspace.getActiveFile();
        if (!currentFile || currentFile.extension !== "md" || !this.obsidianScholar.isFileInNoteLocation(currentFile)) {
          return false;
        } else {
          if (!checking) {
            let paperData = this.obsidianScholar.getPaperDataFromLocalFile(
              currentFile
            );
            if (paperData && paperData.url) {
              fetchSemanticScholarPaperReferences(
                paperData.url
              ).then((references) => {
                new paperReferenceSearchModal(
                  this.app,
                  this.settings,
                  this.obsidianScholar,
                  references.map((reference, index) => {
                    return {
                      paper: reference,
                      paperIndex: index,
                      resultType: "semanticscholar",
                      s2Url: reference.url
                    };
                  }),
                  "Check References for " + paperData.title
                ).open();
              });
            }
          }
          return true;
        }
      }
    });
    this.addCommand({
      id: COMMAND_REMOVE_PAPER,
      name: COMMAND_REMOVE_PAPER_NAME,
      callback: () => {
        const currentFile = this.app.workspace.getActiveFile();
        new paperRemoveModal(
          this.app,
          this.settings,
          this.obsidianScholar,
          currentFile
        ).open();
      }
    });
    this.addCommand({
      id: COMMAND_OPEN_PDF_IN_SYSTEM_APP,
      name: COMMAND_OPEN_PDF_IN_SYSTEM_APP_NAME,
      checkCallback: (checking) => {
        const currentFile = this.app.workspace.getActiveFile();
        if (!currentFile || !import_obsidian5.Platform.isMacOS) {
          return false;
        } else {
          if (!checking) {
            this.obsidianScholar.openPdfWithSystemViewer(
              currentFile
            );
          }
          return true;
        }
      }
    });
    this.addSettingTab(new ObsidianScholarSettingTab(this.app, this));
    this.registerExtensions(["bib"], "markdown");
    this.registerExtensions(["tex"], "markdown");
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var paperSearchModal = class extends import_obsidian5.SuggestModal {
  constructor(app, settings, obsidianScholar) {
    super(app);
    this.lastSearchResults = [];
    this.localPaperData = [];
    this.settings = settings;
    this.obsidianScholar = obsidianScholar;
    const instructions = [
      ["\u2191\u2193", "to navigate"],
      ["\u21B5", "to open"],
      ["shift \u21B5", "to search semanticscholar"],
      ["\u21E5 (tab)", "to expand search result"],
      ["esc", "to dismiss"]
    ];
    const modalInstructionsHTML = this.modalEl.createEl("div", {
      cls: "prompt-instructions"
    });
    for (const instruction of instructions) {
      const modalInstructionHTML = modalInstructionsHTML.createDiv({
        cls: "prompt-instruction"
      });
      modalInstructionHTML.createSpan({
        cls: "prompt-instruction-command",
        text: instruction[0]
      });
      modalInstructionHTML.createSpan({ text: instruction[1] });
    }
    this.setPlaceholder("Enter paper Name");
    this.localPaperData = this.app.vault.getMarkdownFiles().filter((file) => file.path.startsWith(this.settings.NoteLocation)).map((file, index) => {
      return {
        paper: this.obsidianScholar.getPaperDataFromLocalFile(file),
        resultType: "local",
        localFilePath: file.path,
        paperIndex: index
      };
    });
  }
  searchLocalPapers(query) {
    let results = this.localPaperData.filter((paper) => {
      return paper.paper.title.toLowerCase().contains(query.toLowerCase()) || paper.paper.authors.map((author) => author.toLowerCase()).some((author) => author.contains(query.toLowerCase()));
    });
    return results;
  }
  async searchSemanticScholar(query) {
    let searchResult = [];
    try {
      searchResult = await searchSemanticScholar(query);
    } catch (error) {
      new import_obsidian5.Notice("Errors when downloading papers from Semanticscholar");
      console.error(error);
    }
    this.lastSearchResults = searchResult.map((paper, index) => {
      return {
        paper,
        paperIndex: index + this.localPaperData.length,
        resultType: "semanticscholar",
        s2Url: paper.url,
        isFirstS2Result: index === 0
      };
    });
    this.updateSuggestions();
  }
  onOpen() {
    this.keyListener = async (event) => {
      if (event.repeat)
        return;
      if (event.shiftKey && event.key === "Enter") {
        const inputEl = document.querySelector(
          ".prompt-input"
        );
        const query = inputEl.value;
        await this.searchSemanticScholar(query);
      }
      if (event.shiftKey && event.key === "Tab") {
        const selectedItem = document.querySelector(
          ".suggestion-item.is-selected"
        );
        if (selectedItem) {
          selectedItem.classList.toggle("is-added");
        }
      }
      if (!event.shiftKey && event.key === "Tab") {
        const abstractHTML = document.querySelector(
          ".suggestion-item.is-selected > .paper-search-result-abstract"
        );
        if (abstractHTML) {
          abstractHTML.classList.toggle("is-show");
        }
      }
    };
    document.addEventListener("keydown", this.keyListener);
    super.onOpen();
  }
  getSuggestions(query) {
    if (query.trim() === "") {
      return this.localPaperData;
    }
    let result = [];
    let localResults = this.searchLocalPapers(query);
    result = result.concat(localResults);
    result = result.concat(this.lastSearchResults);
    return result;
  }
  renderSuggestion(searchResult, el) {
    if (searchResult.resultType === "semanticscholar") {
      if (searchResult.isFirstS2Result) {
        el.createEl("div", {
          text: "SemanticScholar Search Results",
          cls: "paper-search-result-heading"
        });
      }
    }
    el.createEl("div", {
      text: searchResult.paper.title,
      cls: "paper-search-result-title",
      attr: {
        "data-paper-id": searchResult.paperIndex
      }
    });
    el.createEl("div", {
      text: searchResult.paper.authors.join(", "),
      cls: "paper-search-result-authors"
    });
    el.createEl("div", {
      text: searchResult.paper.abstract,
      cls: "paper-search-result-abstract"
    });
  }
  onChooseSuggestion(searchResult, evt) {
    let allSelectedPaperIds = [];
    this.resultContainerEl.querySelectorAll(".is-added").forEach((el) => {
      let titleEl = el.querySelector(".paper-search-result-title");
      if (titleEl) {
        let paperId = titleEl.getAttribute(
          "data-paper-id"
        );
        if (paperId) {
          allSelectedPaperIds.push(parseInt(paperId));
        }
      }
    });
    console.log(allSelectedPaperIds);
    if (allSelectedPaperIds.length > 0) {
      let papersToDownload = this.lastSearchResults.filter(
        (searchResult2) => {
          return allSelectedPaperIds.includes(
            searchResult2.paperIndex
          );
        }
      );
      console.log(papersToDownload);
      papersToDownload.forEach((searchResult2, index) => {
        new import_obsidian5.Notice(
          "Downloading paper " + (index + 1) + " of " + papersToDownload.length
        );
        this.obsidianScholar.downloadAndSavePaperNotePDF(
          searchResult2.paper
        );
      });
    } else {
      if (searchResult.resultType === "local") {
        const localFilePath = searchResult.localFilePath;
        if (localFilePath) {
          this.obsidianScholar.openPaper(
            localFilePath,
            searchResult.paper
          );
        } else {
          new import_obsidian5.Notice("Local file path not found");
        }
      } else {
        const s2Url = searchResult.s2Url;
        if (s2Url) {
          new import_obsidian5.Notice(NOTICE_DOWNLOADING_S2);
          this.obsidianScholar.downloadAndSavePaperNotePDF(
            searchResult.paper
          );
        } else {
          new import_obsidian5.Notice("S2 URL not found");
        }
      }
    }
  }
  onNoSuggestion() {
    this.resultContainerEl.empty();
  }
  onClose() {
    document.removeEventListener("keydown", this.keyListener);
  }
};
var paperReferenceSearchModal = class extends import_obsidian5.SuggestModal {
  constructor(app, settings, obsidianScholar, currentPapers, headline) {
    super(app);
    this.settings = settings;
    this.obsidianScholar = obsidianScholar;
    this.currentSearchResults = currentPapers;
    const instructions = [
      ["\u2191\u2193", "to navigate"],
      ["\u21B5", "to open"],
      ["\u21E5 (tab)", "to expand search result"],
      ["\u21E7 \u21E5", "to add paper to selection"],
      ["esc", "to dismiss"]
    ];
    const modalInstructionsHTML = this.modalEl.createEl("div", {
      cls: "prompt-instructions"
    });
    for (const instruction of instructions) {
      const modalInstructionHTML = modalInstructionsHTML.createDiv({
        cls: "prompt-instruction"
      });
      modalInstructionHTML.createSpan({
        cls: "prompt-instruction-command",
        text: instruction[0]
      });
      modalInstructionHTML.createSpan({ text: instruction[1] });
    }
    this.setPlaceholder(headline);
  }
  onOpen() {
    this.keyListener = async (event) => {
      if (event.repeat)
        return;
      if (event.shiftKey && event.key === "Tab") {
        const selectedItem = document.querySelector(
          ".suggestion-item.is-selected"
        );
        if (selectedItem) {
          selectedItem.classList.toggle("is-added");
        }
      }
      if (!event.shiftKey && event.key === "Tab") {
        const abstractHTML = document.querySelector(
          ".suggestion-item.is-selected > .paper-search-result-abstract"
        );
        if (abstractHTML) {
          abstractHTML.classList.toggle("is-show");
        }
      }
    };
    document.addEventListener("keydown", this.keyListener);
    super.onOpen();
  }
  getSuggestions(query) {
    if (query.trim() === "") {
      return this.currentSearchResults;
    } else {
      let results = this.currentSearchResults.filter((searchResult) => {
        return searchResult.paper.title.toLowerCase().contains(query.toLowerCase()) || searchResult.paper.authors.map((author) => author.toLowerCase()).some((author) => author.contains(query.toLowerCase()));
      });
      return results;
    }
  }
  renderSuggestion(searchResult, el) {
    el.createEl("div", {
      text: searchResult.paper.title,
      cls: "paper-search-result-title",
      attr: { "data-paper-id": searchResult.paperIndex }
    });
    el.createEl("div", {
      text: searchResult.paper.authors.join(", "),
      cls: "paper-search-result-authors"
    });
    el.createEl("div", {
      text: searchResult.paper.abstract,
      cls: "paper-search-result-abstract"
    });
  }
  onChooseSuggestion(searchResult, evt) {
    let allSelectedPaperIds = [];
    this.resultContainerEl.querySelectorAll(".is-added").forEach((el) => {
      if (el.firstChild) {
        let paperId = el.firstChild.getAttribute(
          "data-paper-id"
        );
        if (paperId) {
          allSelectedPaperIds.push(parseInt(paperId));
        }
      }
    });
    if (allSelectedPaperIds.length > 0) {
      let papersToDownload = this.currentSearchResults.filter(
        (searchResult2) => {
          return allSelectedPaperIds.includes(
            searchResult2.paperIndex
          );
        }
      );
      papersToDownload.forEach((searchResult2, index) => {
        new import_obsidian5.Notice(
          "Downloading paper " + (index + 1) + " of " + papersToDownload.length
        );
        this.obsidianScholar.downloadAndSavePaperNotePDF(
          searchResult2.paper
        );
      });
    } else {
      this.obsidianScholar.downloadAndSavePaperNotePDF(
        searchResult.paper
      );
    }
  }
  onNoSuggestion() {
    this.resultContainerEl.empty();
  }
  onClose() {
    document.removeEventListener("keydown", this.keyListener);
  }
};
var paperRemoveModal = class extends import_obsidian5.SuggestModal {
  constructor(app, settings, obsidianScholar, currentFile) {
    super(app);
    this.localPaperData = [];
    this.settings = settings;
    this.obsidianScholar = obsidianScholar;
    this.currentFile = currentFile;
    const instructions = [
      ["\u2191\u2193", "to navigate"],
      ["\u21B5", "to open"],
      ["\u21E5 (tab)", "to expand search result"],
      ["\u21E7 \u21E5", "to add paper to selection"],
      ["esc", "to dismiss"]
    ];
    const modalInstructionsHTML = this.modalEl.createEl("div", {
      cls: "prompt-instructions"
    });
    for (const instruction of instructions) {
      const modalInstructionHTML = modalInstructionsHTML.createDiv({
        cls: "prompt-instruction"
      });
      modalInstructionHTML.createSpan({
        cls: "prompt-instruction-command",
        text: instruction[0]
      });
      modalInstructionHTML.createSpan({ text: instruction[1] });
    }
    this.setPlaceholder("Type paper to remove");
    this.localPaperData = this.app.vault.getMarkdownFiles().filter((file) => file.path.startsWith(this.settings.NoteLocation)).map((file, index) => {
      return {
        paper: this.obsidianScholar.getPaperDataFromLocalFile(file),
        resultType: "local",
        localFilePath: file.path,
        paperIndex: index
      };
    });
    if (currentFile != null) {
      if (this.localPaperData.some(
        (paper) => paper.localFilePath === currentFile.path
      )) {
        let currentPaper = this.localPaperData.find(
          (paper) => paper.localFilePath === currentFile.path
        );
        if (currentPaper === void 0) {
          throw new Error(
            "Current paper not found in local paper data"
          );
        }
        this.localPaperData = [
          currentPaper,
          ...this.localPaperData.filter(
            (paper) => paper.localFilePath !== currentFile.path
          )
        ];
      }
    }
  }
  searchLocalPapers(query) {
    let results = this.localPaperData.filter((paper) => {
      return paper.paper.title.toLowerCase().contains(query.toLowerCase()) || paper.paper.authors.map((author) => author.toLowerCase()).some((author) => author.contains(query.toLowerCase()));
    });
    return results;
  }
  onOpen() {
    this.keyListener = async (event) => {
      if (event.repeat)
        return;
      if (event.shiftKey && event.key === "Tab") {
        const selectedItem = document.querySelector(
          ".suggestion-item.is-selected"
        );
        if (selectedItem) {
          selectedItem.classList.toggle("is-added");
        }
      }
      if (!event.shiftKey && event.key === "Tab") {
        const abstractHTML = document.querySelector(
          ".suggestion-item.is-selected > .paper-search-result-abstract"
        );
        if (abstractHTML) {
          abstractHTML.classList.toggle("is-show");
        }
      }
    };
    document.addEventListener("keydown", this.keyListener);
    super.onOpen();
  }
  getSuggestions(query) {
    if (query.trim() === "") {
      return this.localPaperData;
    }
    let result = [];
    let localResults = this.searchLocalPapers(query);
    result = result.concat(localResults);
    return result;
  }
  renderSuggestion(searchResult, el) {
    el.createEl("div", {
      text: searchResult.paper.title,
      cls: "paper-search-result-title",
      attr: {
        "data-paper-id": searchResult.paperIndex
      }
    });
    el.createEl("div", {
      text: searchResult.paper.authors.join(", "),
      cls: "paper-search-result-authors"
    });
    el.createEl("div", {
      text: searchResult.paper.abstract,
      cls: "paper-search-result-abstract"
    });
  }
  onChooseSuggestion(searchResult, evt) {
    let allSelectedPaperIds = [];
    this.resultContainerEl.querySelectorAll(".is-added").forEach((el) => {
      if (el.firstChild) {
        let paperId = el.firstChild.getAttribute(
          "data-paper-id"
        );
        if (paperId) {
          allSelectedPaperIds.push(parseInt(paperId));
        }
      }
    });
    if (allSelectedPaperIds.length > 0) {
      let papersToRemove = this.localPaperData.filter((searchResult2) => {
        return allSelectedPaperIds.includes(searchResult2.paperIndex);
      });
      new confirmDeleteModal(
        this.app,
        this.settings,
        this.obsidianScholar,
        papersToRemove.map((paper) => paper.localFilePath).filter(
          (path) => path !== void 0
        )
      ).open();
    } else {
      const localFilePath = searchResult.localFilePath;
      if (localFilePath) {
        new import_obsidian5.Notice("Removing papers from library");
        new confirmDeleteModal(
          this.app,
          this.settings,
          this.obsidianScholar,
          [localFilePath]
        ).open();
      } else {
        new import_obsidian5.Notice("Local file path not found");
      }
    }
  }
  onNoSuggestion() {
    this.resultContainerEl.empty();
  }
  onClose() {
    document.removeEventListener("keydown", this.keyListener);
  }
};
var confirmDeleteModal = class extends import_obsidian5.Modal {
  constructor(app, settings, obsidianScholar, paperPaths) {
    super(app);
    this.settings = settings;
    this.obsidianScholar = obsidianScholar;
    this.paperPaths = paperPaths;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h1", {
      text: "Are you sure to remove the following papers?"
    });
    const paperList = contentEl.createEl("ul");
    this.paperPaths.forEach((paperPath) => {
      paperList.createEl("li", { text: paperPath });
    });
    new import_obsidian5.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("No").onClick(() => {
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Yes").setWarning().onClick(() => {
        this.close();
        this.obsidianScholar.removePaperFromPath(
          this.paperPaths
        );
      })
    );
  }
  onClose() {
    let { contentEl } = this;
    contentEl.empty();
  }
};
var createNoteFromUrlModal = class extends import_obsidian5.Modal {
  constructor(app, settings, obsidianScholar) {
    super(app);
    this.settings = settings;
    this.obsidianScholar = obsidianScholar;
  }
  addInputElementToModal(type) {
    const { contentEl } = this;
    let input = contentEl.createEl(type);
    return input;
  }
  addPropertyToElement(element, property, value) {
    element.setAttribute(property, value);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h4", {
      text: COMMAND_PAPER_MODAL_TITLE,
      cls: "add-paper-title"
    });
    let placeholder = COMMAND_PAPER_MODAL_PLACEHOLDERS[Math.floor(
      Math.random() * COMMAND_PAPER_MODAL_PLACEHOLDERS.length
    )];
    let input = this.addInputElementToModal("input");
    this.addPropertyToElement(input, "type", "search");
    this.addPropertyToElement(input, "placeholder", placeholder);
    this.addPropertyToElement(input, "minLength", "1");
    this.addPropertyToElement(input, "style", "width: 95%;");
    contentEl.createEl("p", {
      text: COMMAND_PAPER_MODAL_DESC,
      cls: "add-paper-description"
    });
    let running = false;
    contentEl.addEventListener("keydown", (event) => {
      if (event.key !== "Enter")
        return;
      let url = input.value.trim().toLowerCase();
      if (!isValidUrl(url)) {
        new import_obsidian5.Notice("Invalid URL");
        return;
      }
      if (!running) {
        running = true;
        this.fetchPaperDataAndCreateNoteFromUrl(url);
      }
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  async fetchPaperDataAndCreateNoteFromUrl(url) {
    let paperFetchFunction;
    if (url.includes("arxiv.org")) {
      new import_obsidian5.Notice(NOTICE_RETRIEVING_ARXIV);
      paperFetchFunction = fetchArxivPaperDataFromUrl;
    } else {
      new import_obsidian5.Notice(NOTICE_RETRIEVING_S2);
      paperFetchFunction = fetchSemanticScholarPaperDataFromUrl;
    }
    paperFetchFunction(url).then(async (paperData) => {
      this.obsidianScholar.downloadAndSavePaperNotePDF(paperData);
    }).catch((error) => {
      new import_obsidian5.Notice(NOTICE_PAPER_NOTE_DOWNLOAD_ERROR);
      console.log(error);
    }).finally(() => {
      this.close();
    });
  }
};
