import os
import json

# Path to the directory where the notes will be created
directory_path = r'E:\_GIT\obsidian\BoA timeline\profiles\people'

# Mapped officer names
officer_name_map = {
    "WISSINGER, PETER J": ["PETER J WISSINGER"],
    "PRICE, JAY": ["JAY PRICE"],
    "STEPHENS, KELLY D": ["KELLY D STEPHENS"],
    "MCCLELLAND, STEVEN D": ["STEVEN D MCCLELLAND", "STEVEN D. MCCLELLAND", "STEVE D. MCCLELLAND"],
    "OLSEN, KRISTINE": ["KRISTINE OLSEN"],
    "CAREY, PATRICK": ["PATRICK CAREY"],
    "MORRISON, STEPHEN D.": ["STEPHEN D. MORRISON", "STEPHEN MORRISON", "STEPHEN D MORRISON"],
    "PARKER, EDWARD R": ["EDWARD R PARKER"],
    "HEID, MICHAEL": ["MICHAEL HEID", "MICHAEL J. HEID"],
    "LOUGHLIN, MICHAEL J.": ["MICHAEL J. LOUGHLIN"],
    "HAIRR, LISA M.": ["LISA M. HAIRR"],
    "ALLEN, KEVIN": ["KEVIN ALLEN"],
    "SPARKMAN, KENDALL": ["KENDALL SPARKMAN"],
    "MOORE, NICHOLAS G.": ["NICHOLAS G. MOORE"],
    "HEITZ, KELLY N": ["KELLY N HEITZ", "KELLY HEITZ", "KELLY NICHOLAS HEITZ", "HEITZ, KELLY NICHOLAS"],
    "HARRISON, MARY J.": ["MARY J. HARRISON"],
    "MERKLE, GREG": ["GREG MERKLE"],
    "FAHEY, MICHAEL G.": ["MICHAEL G. FAHEY"],
    "MOCK, BUNNY": ["BUNNY MOCK"],
    "SARGETAKIS, PAULA SWANER": ["PAULA SWANER SARGETAKIS"],
    "RHEIN, KEVIN A.": ["KEVIN A. RHEIN"],
    "LUKENBILL, STEVEN A": ["STEVEN A LUKENBILL"],
    "CANTWELL, JAMES CLAIR": ["JAMES CLAIR CANTWELL"],
    "CALLAGHAN, PATRICIA R.": ["PATRICIA R. CALLAGHAN"],
    "SCHINDLER, AUSTIN": ["AUSTIN SCHINDLER"],
    "SCOVEL, MATTHEW WADE": ["MATTHEW WADE SCOVEL"],
    "SLOAN, TIMOTHY J.": ["TIMOTHY J. SLOAN"],
    "ADAMS, STEPHEN W": ["STEPHEN W ADAMS"],
    "GUESS, DON": ["DON GUESS"],
    "ADAMS, S CRAIG": ["S CRAIG ADAMS", "CRAIG ADAMS", "S. CRAIG ADAMS"],
    "STEELE, JAMES M": ["JAMES M STEELE"],
    "WISSINGER, PETER": ["PETER WISSINGER"],
    "HAYWARD, BRENT H": ["BRENT H HAYWARD"],
    "STUMPF, JOHN G.": ["JOHN G. STUMPF"],
    "WHITE, DANIEL PAUL": ["DANIEL PAUL WHITE"],
    "STEWART, TIMOTHY A": ["TIMOTHY A STEWART"],
    "CARLSTON, SCOTT": ["SCOTT CARLSTON"],
    "WILLIAMS, DANIEL G": ["WILLIAMS, DANIEL G"],
    "CHAPMAN, ROBERT K": ["ROBERT K CHAPMAN", "ROBERT K. CHAPMAN", "ROBERT CHAPMAN", "CHAPMAN, ROBERT"],
    "MUELLER, NATHAN": ["NATHAN MUELLER", "NATE MUELLER", "NATE WILLIAM MUELLER"],
    "MALLOY, RICHARD F.": ["RICHARD F. MALLOY", "MALLOY, RICHARD F", "RICHARD F MALLOY", "MORRISON, STEPHEN"],
    "LEVY, RICHARD D.": ["RICHARD D. LEVY", "RICHARD D LEVY"],
    "BRENAY, MARK F": ["MARK F BRENAY"],
    "HAMBLIN, SCOTT WEALTH": ["SCOTT WEALTH HAMBLIN"],
    "JOHNSON, EDWARD": ["EDWARD JOHNSON"],
    "BAKE, KAROLYN": ["KAROLYN BAKE", "KAROLYN BAKER"],
    "FAHEY, JOHN": ["JOHN FAHEY"],
    "JEWELL, MICHAEL D": ["MICHAEL D JEWELL", "MICHAEL JEWELL"],
    "TOLSTEDT, CARRIE L.": ["CARRIE L. TOLSTEDT"],
    "KNOBLOCH, MARK": ["MARK KNOBLOCH"],
    "MOSKOWITZ, DAVID": ["DAVID MOSKOWITZ", "DAVID A. STEWART", "DAVID MOSCOWITZ"],
    "HOLLAND, MONIQUE": ["MONIQUE HOLLAND"],
    "SHREWSBERRY, JOHN R.": ["JOHN R. SHREWSBERRY"],
    "HARDISON, HOPE A.": ["HOPE A. HARDISON"],
    "PARDEN, PATTY J": ["PATTY J PARDEN"],
    "CODEL, FRANKLIN R": ["FRANKLIN R CODEL"],
    "TOWNS, PATRICIA A": ["PATRICIA A TOWNS"],
    "GAREISS, NEIL": ["NEIL GAREISS"],
    "GARBER, DANIEL A": ["DANIEL A GARBER"],
    "WARNER, DEANNA": ["DEANNA WARNER"],
    "STEWARD, DARCY": ["DARCY STEWART"],
    "BANERRJI, ARINDAM": ["ARINDAM BANERRJI"],
    "WHITE, JON": ["JON WHITE"],
    "DURSTELER, BLAKE": ["BLAKE DURSTELER"],
    "MOORE, ROB": ["ROB MOORE"],
    "MACINTYRE, M. ANGIE": ["M. ANGIE MACINTYRE"],
    "SOBER, CAROL": ["CAROL SOBER"],
    "LEA-KAHLE, DIANA": ["DIANA LEA-KAHLE"],
    "MODJTABAI, AVID": ["AVID MODJTABAI"],
    "RUESCH, CHORTNEY B": ["CHORTNEY B RUESCH"],
    "CROSBY, RILEY": ["RILEY CROSBY"],
    "NIELSON, DYLAN": ["DYLAN NIELSON"],
    "WARNER, NATHAN B": ["NATHAN B WARNER"],
    "LYNCH, JAMES D": ["JAMES D LYNCH", "JAMES LYNCH"],
    "CAMPBELL, ELAINE P.": ["ELAINE P. CAMPBELL"],
    "MENDEZ, RAFAEL A": ["RAFAEL A MENDEZ"],
    "SULLIVAN, SCOTT": ["SCOTT SULLIVAN"],
    "CAMPBELL, JON R": ["JON R CAMPBELL"],
    "RINGLER, DIANE": ["DIANE RINGLER"],
    "COFFIN, MARY C.": ["MARY C. COFFIN"],
    "CUNHA FILHO, ANTONIO FRANCISCO": ["ANTONIO FRANCISCO CUNHA FILHO"],
    "MOCK, ERIC": ["ERIC MOCK", "ERIC STEVEN MOCK"],
    "STROTHER, JAMES": ["JAMES STROTHER", "JAMES M STROTHER", "JAMES M. STROTHER"],
    "LUKENBILL, STEVEN": ["STEVEN LUKENBILL"],
    "WESCOTT, MARTIN": ["MARTIN WESCOTT"],
    "HENRY, TRISH": ["TRISH HENRY"],
    "GARCIA, MONICA O": ["MONICA O GARCIA"],
    "KRUEGER, LIBBY": ["KRUEGER, LIBBY", "KRUEGER , LIBBY", "LIBBY KRUEGER"],
    "BENNET, STEPHEN G": ["STEPHEN G BENNET"],
    "MUELLER, BROOKE": ["BROOKE MUELLER"],
    "HEITZ, KENT E": ["KENT E HEITZ"],
    "WATKINS, DON N": ["DON N WATKINS"],
    "SMALL, JEFF": ["JEFF SMALL"],
    "MUNCY, KEITH G.": ["KEITH G. MUNCY"],
    "KING-DARBY, SUE C.": ["SUE C. KING-DARBY"],
    "MANESS, CHAD": ["MANESS, CHAD"],
    "STOCKING, JAY": ["JAY STOCKING"],
    "SCALLON, ROBERT": ["ROBERT SCALLON"],
    "MILLECAM, KENT": ["KENT MILLECAM"],
    "SCOVEL, JENNIFER JANE": ["JENNIFER JANE SCOVEL"],
    "MILLER, TROY GARY": ["TROY GARY MILLER"],
    "CARROLL, DAVID M.": ["DAVID M. CARROLL"],
    "WALLIN, RICHARD D": ["RICHARD D WALLIN"],
    "KELLER, MICHAEL J.": ["MICHAEL J. KELLER", "MICHAEL J KELLER"],
    "SWANER, PAULA M": ["PAULA M SWANER"]
}

# Ensure the directory exists
os.makedirs(directory_path, exist_ok=True)

for officer, aliases in officer_name_map.items():
    file_name = f"{officer.replace('.', '')}.md"  # Remove periods from the file name
    file_path = os.path.join(directory_path, file_name)
    with open(file_path, 'w') as file:
        if aliases:
            file.write("---\naka:\n")
            for alias in aliases:
                file.write(f"- {alias}\n")
            file.write("---\n")

print("Notes have been created successfully.")
